plugins {
    id 'java-library'
    id 'org.springframework.boot' version '4.+'
    id 'io.spring.dependency-management' version '1.+'
}

group = 'uk.gov.fco.documentupload'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    enabled = false
    archiveFileName = bootJar.archiveFileName
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('software.amazon.awssdk:bom:2.+')
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:sts'
    implementation 'software.amazon.awssdk:rekognition'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.+'

    implementation 'fi.solita.clamav:clamav-client:1.0.+'
    implementation 'org.apache.pdfbox:pdfbox:3.0.+'
    implementation 'org.apache.pdfbox:pdfbox-tools:3.0.+'
    implementation 'org.apache.tika:tika-core:3.3.+'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    if (System.getProperty("os.name").toLowerCase().contains("mac") &&
            System.getProperty("os.arch").toLowerCase().contains("aarch64")) {
        runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.+:osx-aarch_64'
    }
}

tasks.named('test') {
    useJUnitPlatform()
    maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
}

