
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 70MB

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 9000
  servlet:
    context-path: /v1

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}
    org.apache: INFO
    org.springframework: INFO

antivirus:
  enabled: ${ANTIVIRUS_ENABLED:false}
  host: ${ANTIVIRUS_HOST:localhost}
  port: ${ANTIVIRUS_PORT:3310}
  timeout: ${ANTIVIRUS_TIMEOUT:30000}

storage:
  engine: ${STORAGE_ENGINE:file}
  file:
    location: /tmp
  s3:
    bucket: ${S3_BUCKET}

---

spring:
  profiles: production
